name: Add Entry to Database
description: Suggest a new entry for the SQLite database
title: "[DB] Add: <short description>"
labels: ["db-add"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the template
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: Short description of the template.
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Name of the author
      required: true
  - type: input
    id: author_url
    attributes:
      label: Author URL
      description: URL used to find the author
      required: true
  - type: input
    id: clone_url
    attributes:
      label: Clone URL
      description: Public URL for cloning the template
      required: true
