name: Validate Repository

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-repository:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Try Seed Database
        run: |
          cd dist
          go run ../ seed